"""alteracao do Banco para imagem nao ser obrigatoria

Revision ID: 5ef64977c1d8
Revises: cb54efdf8ed7
Create Date: 2025-08-31 13:36:44.825877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef64977c1d8'
down_revision = 'cb54efdf8ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
